spring.application.name=Spring Boot Web Tutorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/nupurgupta/Documents/springBootWebTutorial/db
spring.datasource.username=tushar
spring.datasource.password=tushar123
spring.jpa.hibernate.ddl-auto=update
